config/routes.rb
Kirsh::Application.routes.draw do


  get "help_informations/index"
  get "help_informations/new"
  get "help_informations/edit"
  get "select_objects/new"
  get "select_objects/edit"
  mount Ckeditor::Engine => '/ckeditor'
  root 'sites#index'


  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  get 'admin' => 'admins#index'
  get 'yamail' => 'sites#yamail'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :user_accounts
  resources :effective_rieltors
  resources :personals
  resources :client_requests do
    post :load_request, on: :collection
    post :check_phone, on: :collection
  end
  resources :client_request_without_objects do
    post :load_request, on: :collection
  end
  resources :sale_objects do
    member do
      patch :hot_offer
      patch :avans
      patch :sold
      patch :expired
      get :photo_delete
    end
    resources :photo, only: [:create, :destroy]
    post :getDistricts, on: :collection
    post :filter, on: :collection
  end
  resources :sites do
   collection do
    get :about
    get :question_answer
    get :contacts
    get :zalog
    get :buyout
    get :kredit
    get :agents
    get :own_biznes
    get :developer
    get :owner_komerch
    get :search
    post :search_request
    get :request_user
    get :request_advert
    post :send_request
    post :send_request_advert
    post :question_answer_create
    post :consultant
    post :search_map
    get :map_site
    get :map_site_print
    get :document_example
   end
   get :object_detail, on: :member
   get :print, on: :member
  end
  resources :abouts
  resources :answers
  resources :developers
  resources :owner_komerches
  resources :kredits
  resources :zalogs
  resources :buyouts
  resources :bisnes_selfs
  resources :agents
  resources :regions
  resources :news_on_sites do
    get :admin_index, on: :collection
    get :public, on: :member
  end
  resources :main_pages
  resources :districts
  resources :seos
  resources :top_banners
  resources :papers do
    get :site_index, on: :collection
  end
  resources :tests
  resources :select_objects
  resources :help_informations

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/agent.rb
class Agent < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  accepts_nested_attributes_for :question
end

app/models/buyout.rb
class Buyout < ActiveRecord::Base
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_one :client_request

	validates :phone, :name, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/developer.rb
class Developer < ActiveRecord::Base
end

app/models/district.rb
class District < ActiveRecord::Base
	belongs_to :region
end

app/models/foreign.rb
class Foreign < ActiveRecord::Base
end

app/models/franshisa.rb
class Franshisa < ActiveRecord::Base
end

app/models/kredit.rb
class Kredit < ActiveRecord::Base
end

app/models/paper.rb
class Paper < ActiveRecord::Base
	 mount_uploader :file, FileUploader
	 validates :title, presence: true
end

app/models/partner.rb
class Partner < ActiveRecord::Base
end

app/models/personal.rb
class Personal < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
	belongs_to :user_account
	has_many :client_requests
    has_many :sale_objects, dependent: :nullify 


	scope :rieltor, -> {where(position: 15)}

	validates :sename, :name, :status, :position, :agency, :begin_job, :mobile_phone, presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	# mount_uploader :photo, PhotoUploader
	belongs_to :sale_object, polymorphic: true 
end

app/models/question.rb
# encoding: utf-8

class Question < ActiveRecord::Base
	apply_simple_captcha :message => "Не правильно введен код с картинки"
	has_one :answer, dependent: :destroy 
	validates :name, :question, :email, presence: true

	scope :public, ->{where(is_public: 1)}

end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :districts
end

app/models/seo.rb
class Seo < ActiveRecord::Base
end

app/models/test.rb
class Test 
	include ActiveModel::Model
	
	attr_accessor :fio, :email, :phone, :question1, :question2, :question3, :question4, :question5, :question6

	validates :fio, :email, :phone, presence: true

	def summ
		question1.to_i+question2.to_i+question3.to_i+question4.to_i+question5.to_i+question6.to_i
	end

end

app/models/zalog.rb
class Zalog < ActiveRecord::Base
end

app/controllers/effective_rieltors_controller.rb
class EffectiveRieltorsController < ApplicationController
  def index
    @results = {}     
  	if params[:filter].presence
     @from = params[:filter][:from]
     @to = params[:filter][:to]   	 
     @effective = Personal.where(id: SaleObject.select(:personal_id).where(begin_contract: @from..@to)).order(:sename) unless params[:status].present?
     @effective = Personal.where(id: SaleObject.select(:personal_id).where(begin_contract: @from..@to)).where(status: 1).order(:sename) if params[:status].present?

  	else        	 
     @effective = Personal.all.order(:sename) unless params[:status].present?
     @effective = Personal.where(status: 1).order(:sename) if params[:status].present?
  	end    
  end
  
  def new
  end

  def edit
  end

  def show
    if params[:filter].presence
     from = params[:filter][:from]
     to = params[:filter][:to]
     active = params[:filter][:active].to_i  
     filter = {}
     filter[:begin_contract] = [from..to] unless from.blank? && to.blank?
     filter[:status] = [3,4] unless active.zero?    
    end
   @rieltor = SaleObject.where(personal_id: params[:id]).where(filter)
  end

end

app/helpers/effective_rieltors_helper.rb
module EffectiveRieltorsHelper
end

app/views/effective_rieltors/edit.html.slim
h1 EffectiveRieltors#edit
p Find me in app/views/effective_rieltors/edit.html.slim

app/views/effective_rieltors/index.html.slim
=content_for :links do
 .filter=form_for :filter, url: {action: :index}, html: {method: :get} do |f|
  .field
   =f.label :from, "С:", style: "font-size: 18px;font-weight: bold; width: 10px;display: inline-block; padding-right: 40px; text-align: right"
   =date_field('filter', 'from', value: @from, style: "width: 130px;")
  .field
   =f.label :to, "По:", style: "font-size: 18px;font-weight: bold; width: 10px;display: inline-block; padding-right: 40px;text-align: right"
   =f.date_field :to, value: @to, style: "width: 130px;"     
   =link_to "Применить", "#", onclick: "$('form').submit()"
 p=link_to "Назад", admin_path
 br
 -unless params[:status].present?
  p=link_to "Показать только работающих сотрудников", effective_rieltors_path(status: 1) 
 -if params[:status].present?
  p=link_to "Показать всех сотрудников", effective_rieltors_path 
table.result
 tr
  th.head colspan='3' Риэлторы
  th.head colspan='3' Объекты
  th.head colspan='3' Проспекты
 tr
  th №
  th ФИО
  th Нач. работы
  th.vertical Соглашения
  th.vertical Договоры
  th.vertical Активн.
  th.vertical Обращения
  th.vertical Заинтересов
  th.vertical %
 -i = 0
 -@effective.each do |result|
  tr
   td=i+=1
   td style="text-align:left"=link_to "#{result.sename} #{result.name}", effective_rieltor_path(result)
   td=result.begin_job.strftime("%d.%m.%Y")
   td=result.sale_objects.agreement.count
   td=result.sale_objects.contract.count
   td=result.sale_objects.where(status: [3,4]).count
   td=treatment = result.client_requests.treatment.count
   td=accompanied = result.client_requests.accompanied.count
   td=(accompanied/treatment)*100 unless treatment.zero?

app/views/effective_rieltors/new.html.slim
h1 EffectiveRieltors#new
p Find me in app/views/effective_rieltors/new.html.slim

app/views/effective_rieltors/show.html.slim
=content_for :links do
 .filter=form_for :filter, url: {action: :show}, html: {method: :get} do |f|
  .field
   =f.label :from, "С:", style: "font-size: 18px;font-weight: bold; width: 10px;display: inline-block; padding-right: 40px; text-align: right"
   =f.date_field :from, style: "width: 130px;" 
  .field
   =f.label :to, "По:", style: "font-size: 18px;font-weight: bold; width: 10px;display: inline-block; padding-right: 40px;text-align: right"
   =f.date_field :to, style: "width: 130px;"
  .field
   =f.check_box :active, style: "float: left; margin-right: 10px;"
   =f.label :active, "Активные", style: "display: inline; margin-right: 40px;"
   =link_to "Применить", "#", onclick: "$('form').submit()"
 p=link_to "Назад", effective_rieltors_path
table.result
 tr
  th.head colspan='4' Недвижимость
  th.head colspan='3' Покупатели
 tr
  th №
  th Адрес
  th Начало
  th Окончание 
  th.vertical Обращения
  th.vertical Заинтересов
  th.vertical %
 -i = 0
 -@rieltor.each do |result|
  tr
   td=i+=1
   -unless result.status == 3 || result.status == 4 
    td style="text-align:left;"= link_to "#{getRegionName result.region}, #{result.street_type} #{result.street}, (#{result.owner_phone})", edit_sale_object_path(result), style: "color:#828282" 
   -else 
    td style="text-align:left"= link_to "#{getRegionName result.region}, #{result.street_type} #{result.street}, (#{result.owner_phone})", edit_sale_object_path(result)
   td=result.begin_contract.strftime("%d.%m.%Y") unless result.begin_contract.nil?  
   td=result.end_contract.strftime("%d.%m.%Y") unless result.end_contract.nil?  
   td= status_1 = result.client_requests.where(status: 1).count()
   td= status_2 = result.client_requests.where(status: [2,3]).count()
   td=(status_2/status_1)*100 unless status_1.zero?