config/routes.rb
Kirsh::Application.routes.draw do


  get "help_informations/index"
  get "help_informations/new"
  get "help_informations/edit"
  get "select_objects/new"
  get "select_objects/edit"
  mount Ckeditor::Engine => '/ckeditor'
  root 'sites#index'


  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  get 'admin' => 'admins#index'
  get 'yamail' => 'sites#yamail'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :user_accounts
  resources :effective_rieltors
  resources :personals
  resources :client_requests do
    post :load_request, on: :collection
    post :check_phone, on: :collection
  end
  resources :client_request_without_objects do
    post :load_request, on: :collection
  end
  resources :sale_objects do
    member do
      patch :hot_offer
      patch :avans
      patch :sold
      patch :expired
      get :photo_delete
    end
    resources :photo, only: [:create, :destroy]
    post :getDistricts, on: :collection
    post :filter, on: :collection
  end
  resources :sites do
   collection do
    get :about
    get :question_answer
    get :contacts
    get :zalog
    get :buyout
    get :kredit
    get :agents
    get :own_biznes
    get :developer
    get :owner_komerch
    get :search
    post :search_request
    get :request_user
    get :request_advert
    post :send_request
    post :send_request_advert
    post :question_answer_create
    post :consultant
    post :search_map
    get :map_site
    get :map_site_print
    get :document_example
   end
   get :object_detail, on: :member
   get :print, on: :member
  end
  resources :abouts
  resources :answers
  resources :developers
  resources :owner_komerches
  resources :kredits
  resources :zalogs
  resources :buyouts
  resources :bisnes_selfs
  resources :agents
  resources :regions
  resources :news_on_sites do
    get :admin_index, on: :collection
    get :public, on: :member
  end
  resources :main_pages
  resources :districts
  resources :seos
  resources :top_banners
  resources :papers do
    get :site_index, on: :collection
  end
  resources :tests
  resources :select_objects
  resources :help_informations

end

app/controllers/sale_objects_controller.rb
# encoding: utf-8

class SaleObjectsController < ApplicationController
    
  before_filter only: [:new, :edit, :create, :update] do 
    @personals = {}
    @regions = {}
    @districts = []
    Personal.where(status: 1).order('sename ASC').each {|porsona| @personals["#{porsona.sename} #{porsona.name}"] = porsona.id }
    Region.all.order('name ASC').each { |region|  @regions[region.name] = region.id}    
    region = Region.first
    if !region.nil? && region.districts.any?
     region.districts.each do |district|
      @districts << district.name
     end
    end
  end

   before_filter only: [:index, :filter] do
    
    @streets = []
    SaleObject.all.order("street ASC").group(:street).each { |street|  @streets << street.street}    
  end  

  def index      
      @sale_objects = SaleObject.all   
      @count = @sale_objects.count
  end

  def new    
  	@sale_object = SaleObject.new
    # 3.times {@sale_object.photos.build   }
  	# @sale_object.photo = params[:file]
  end

  def create
    # render text: post_params
    @sale_object = SaleObject.new(
      region: params[:sale_object][:region],
      locality_type: params[:sale_object][:locality_type],
      locality: params[:sale_object][:locality],
      area: params[:sale_object][:area],
      district: params[:sale_object][:district],
      street_type: params[:sale_object][:street_type],
      street: params[:sale_object][:street],
      object_type: params[:sale_object][:object_type],
      object: params[:sale_object][:object],
      letter: params[:sale_object][:letter],
      show_number: params[:sale_object][:show_number],
      block_type: params[:sale_object][:block_type],
      block: params[:sale_object][:block],
      flat: params[:sale_object][:flat],
      index: params[:sale_object][:index],
      station_metro: params[:sale_object][:station_metro],
      agency: params[:sale_object][:agency],
      personal_id: params[:sale_object][:personal_id],
      status: params[:sale_object][:status],
      begin_contract: params[:sale_object][:begin_contract],
      end_contract: params[:sale_object][:end_contract],
      owner: params[:sale_object][:owner],
      owner_phone: params[:sale_object][:owner_phone],
      price: params[:sale_object][:price],
      hide_price: params[:sale_object][:hide_price],
      client_request: params[:sale_object][:client_request],
      client_phone: params[:sale_object][:client_phone],
      finaly_price: params[:sale_object][:finaly_price],
      date: params[:sale_object][:date],
      structure_type: params[:sale_object][:structure_type],
      nswe: params[:sale_object][:nswe],
      rooms_count: params[:sale_object][:rooms_count],
      general_square: params[:sale_object][:general_square],
      live_square: params[:sale_object][:live_square],
      kittchen_square: params[:sale_object][:kittchen_square],
      area_square: params[:sale_object][:area_square],
      sanysel: params[:sale_object][:sanysel],
      material: params[:sale_object][:material],
      state: params[:sale_object][:state],
      new_old: params[:sale_object][:new_old],
      land: params[:sale_object][:land],
      owner_form: params[:sale_object][:owner_form],
      floor: params[:sale_object][:floor],
      all_floors: params[:sale_object][:all_floors],
      balkon: params[:sale_object][:balkon],
      lodjiya: params[:sale_object][:lodjiya],
      parking: params[:sale_object][:parking],
      garage: params[:sale_object][:garage],
      lift: params[:sale_object][:lift],
      phone_line: params[:sale_object][:phone_line],
      description: params[:sale_object][:description],
      agreement: params[:sale_object][:agreement],
      new_old: params[:sale_object][:new_old], 
      owner_form: params[:sale_object][:owner_form], 
      land: params[:sale_object][:land], 
      line: params[:sale_object][:line], 
      buildings_count: params[:sale_object][:buildings_count], 
      building_square: params[:sale_object][:building_square], 
      id: params[:id])
    if @sale_object.save
      10.times do |i|
       i += 1
       unless  params[:sale_object]['photo'+i.to_s].nil? 
        photo = params[:sale_object]['photo'+i.to_s][0]
        @sale_object.photo_upload photo, @sale_object.id
        Photo.create(sale_object_id: @sale_object.id, photo: photo.original_filename)
       end
      end    
      redirect_to sale_objects_path, notice: "Объект отредактирован"
     else
      render 'new'
     end      
  end

  def edit
     @sale_object = SaleObject.find params[:id]     
     @sale_object.object.gsub!(/[А-Я]*[а-я]*/,"")
     @sale_object.block.gsub!(/[А-Я]*[а-я]*\./,"")  
     # 3.times {@sale_object.photos.build   }     
  end

  def update    
    @sale_object = SaleObject.find params[:id]     
    if @sale_object.update(
      region: params[:sale_object][:region],
      locality_type: params[:sale_object][:locality_type],
      locality: params[:sale_object][:locality],
      area: params[:sale_object][:area],
      district: params[:sale_object][:district],
      street_type: params[:sale_object][:street_type],
      street: params[:sale_object][:street],
      object_type: params[:sale_object][:object_type],
      object: params[:sale_object][:object],
      letter: params[:sale_object][:letter],
      show_number: params[:sale_object][:show_number],
      block_type: params[:sale_object][:block_type],
      block: params[:sale_object][:block],
      flat: params[:sale_object][:flat],
      index: params[:sale_object][:index],
      station_metro: params[:sale_object][:station_metro],
      agency: params[:sale_object][:agency],
      personal_id: params[:sale_object][:personal_id],
      status: params[:sale_object][:status],
      begin_contract: params[:sale_object][:begin_contract],
      end_contract: params[:sale_object][:end_contract],
      owner: params[:sale_object][:owner],
      owner_phone: params[:sale_object][:owner_phone],
      price: params[:sale_object][:price],
      hide_price: params[:sale_object][:hide_price],
      client_request: params[:sale_object][:client_request],
      client_phone: params[:sale_object][:client_phone],
      finaly_price: params[:sale_object][:finaly_price],
      date: params[:sale_object][:date],
      structure_type: params[:sale_object][:structure_type],
      nswe: params[:sale_object][:nswe],
      rooms_count: params[:sale_object][:rooms_count],
      general_square: params[:sale_object][:general_square],
      live_square: params[:sale_object][:live_square],
      kittchen_square: params[:sale_object][:kittchen_square],
      area_square: params[:sale_object][:area_square],
      sanysel: params[:sale_object][:sanysel],
      material: params[:sale_object][:material],
      state: params[:sale_object][:state],
      new_old: params[:sale_object][:new_old],
      land: params[:sale_object][:land],
      owner_form: params[:sale_object][:owner_form],
      floor: params[:sale_object][:floor],
      all_floors: params[:sale_object][:all_floors],
      balkon: params[:sale_object][:balkon],
      lodjiya: params[:sale_object][:lodjiya],
      parking: params[:sale_object][:parking],
      garage: params[:sale_object][:garage],
      lift: params[:sale_object][:lift],
      phone_line: params[:sale_object][:phone_line],
      description: params[:sale_object][:description],
      agreement: params[:sale_object][:agreement],
      new_old: params[:sale_object][:new_old], 
      owner_form: params[:sale_object][:owner_form], 
      land: params[:sale_object][:land], 
      line: params[:sale_object][:line], 
      buildings_count: params[:sale_object][:buildings_count], 
      building_square: params[:sale_object][:building_square], 
      id: params[:id])
      10.times do |i|
       i += 1
       unless  params[:sale_object]['photo'+i.to_s].nil? 
        photo = params[:sale_object]['photo'+i.to_s][0]
        @sale_object.photo_upload photo, @sale_object.id
        Photo.create(sale_object_id: @sale_object.id, photo: photo.original_filename)
       end
      end    
      redirect_to sale_objects_path, notice: "Объект отредактирован"
     else
      render 'edit'
     end      
  end

  def show
  end

  def destroy
    if SaleObject.find(params[:id]).destroy
      redirect_to sale_objects_path, notice: "Объект был удален"
    else
      redirect_to sale_objects_path, notice: "Объект не был удален"
    end
  end

  def hot_offer
    offer = SaleObject.find params[:id_ob]
    offer.update(hot_offer: params[:val])  
    render nothing: true       
  end

  def avans
    sale_object = SaleObject.find(params[:id])
    if sale_object.update(avans: true, sold: false, expired: false, status: 5)
      effective_rieltors sale_object
      redirect_to edit_sale_object_path(params[:id])
    else
      render 'edit'
    end
  end

  def sold
    sale_object = SaleObject.find(params[:id])
    if sale_object.update(sold: true, expired: false, avans: false, status: 6)
      effective_rieltors sale_object
      redirect_to edit_sale_object_path(params[:id])
    else
      render 'edit'
    end
  end

  def expired
    sale_object = SaleObject.find(params[:id])
    if sale_object.update(expired: true, avans: false, sold: false, status: 7)  
      effective_rieltors sale_object
      redirect_to edit_sale_object_path(params[:id])
    else
      render 'edit'
    end
  end

  def photo_delete
    photo = Photo.find(params[:file_id])
    if photo.destroy
      File.delete(Rails.root.join('public','sale_objects',photo.sale_object_id.to_s,"small_#{photo.photo}"))
      File.delete(Rails.root.join('public','sale_objects',photo.sale_object_id.to_s,"medium_#{photo.photo}"))
      File.delete(Rails.root.join('public','sale_objects',photo.sale_object_id.to_s,"original_#{photo.photo}"))
      redirect_to edit_sale_object_path(photo.sale_object_id), notice: "Фотография была удалена"
    else
      redirect_to edit_sale_object_path(photo.sale_object_id), notice: "Фотография не была удалена"

app/helpers/sale_objects_helper.rb
# encoding: utf-8

module SaleObjectsHelper
	
	def getLocalityType
		{'город' => "гор.","ПГТ" => "ПГТ", "поселок" => "пос.", "деревня" => "дер.", "станция" => "ст.", "станица" => "станица", "село" => "сел.", "хутор" => "хут." }
	end

	def getStreetType
		{"улица" => "ул.", "проспект" => "просп.", "проезд" => "проезд", "бульвар" => "бул.", "шоссе" => "шос.", "переулок" => "пер.", "площадь" => "пл.", "тупик" => "туп.", "жилмассив" => "жилм.", "микрорайон" => "м-р."}
	end

	def getObjectType
		["дом", "участок", "владение"]
	end

	def getBlockType
		{"корпус" => "кор.", "строение" => "стр.", "блок" => "бл."}
	end

	def getOperator
		['Пенза-Центральное'] 
	end

	def getStatus
		{"На продажу" => 3,"в аренду" => 4,"под авансом" => 5,"продано/сдано" => 6,"истек срок договора" => 7,"юр сопровождение" => 8}
	end

	def getStatusName id
		 getStatus.key(id)
	end

	def getRegionName id
		Region.find(id).name
	end

	def getType
		["Квартиры","Комнаты","Городские дома","Загородные дома","Зем.участки","Гаражи","Дачи", "Коммерческая недвижимость"]
	end
	def getType2
		["Квартиры","Комнаты","Городские дома","Загородные дома","Зем.участки","Гаражи","Дачи"]
	end

	def getTypeLived
		["Квартиры","Комнаты","Городские дома","Загородные дома","Зем.участки","Гаражи","Дачи"]
	end

	def getTypeCommerc
		["Торговые помещения","Производственные помещения","Складские помещения","Офисные помещения","Ком. недвижимость различного назначения","Участки под коммерческую застройку"]
	end

	def getTypeAll
		["Квартиры","Комнаты","Городские дома","Загородные дома","Зем.участки","Гаражи","Дачи","Торговые помещения","Производственные помещения","Складские помещения","Офисные помещения","Ком. недвижимость различного назначения","Участки под коммерческую застройку"]
	end

	def getTypeLivedString
		"Квартиры,Комнаты,Городские дома,Загородныедома,Зем. участки,Гаражи,Дачи"
	end

	def getTypeCommercString
		"Все предложения,Торговые помещения,Производственные помещения,Складские помещения,Офисные помещения,Ком. недвижимость различного назначения,Участки под коммерческую застройку"
	end

	def getMaterial
		["панель","блоки","кирпич","монолит","дерево","брус","другое"]
	end

	def getSanysel
		["Совмещенный", "Раздельный", "Несколько", "во дворе", "нет"]
	end

	def getState
		["Требует ремонта", "Косметический ремонт", "сост. хорошее", "евроремонт", "другое"]
	end

	def getAdressString object
		"#{object.agreement.zero? ? '' : '<span class=agreement>[по соглашению]</span> <br />' }#{object.locality_type}#{object.locality} #{object.district} р-н. #{object.street_type}#{object.street} #{object.object_type} #{object.object}#{object.letter} #{object.block_type unless object.block.blank?} #{object.block}".html_safe
	end

	def getAdressStringSite object
		"#{object.locality_type}#{object.locality} #{object.district} р-н. #{object.street_type}#{object.street} #{object.object_type if object.show_number == 1} #{object.object if object.show_number == 1}#{object.letter if object.show_number == 1}  #{object.block_type unless object.block.blank?} #{object.block}".html_safe
	end

	# def getAdressStringForMap object
	# 	"q=Россия+#{object.locality.strip}+#{object.street_type.strip}+#{object.street.strip}+#{object.object.strip}#{object.letter.strip}+#{object.block_type.strip}#{object.block.strip}".html_safe		
	# end

	# def getAreas
	# 	['Агинский Бурятский автономный округ',	'Алтайский край',	'Амурская область',	'Архангельская область',	'Астраханская область',	'Белгородская область',	'Брянская область',	'Владимирская область',	'Волгоградская область',	'Вологодская область',	'Воронежская область',	'Еврейская автономная область',	'Ивановская область',	'Ингушетия',	'Иркутская область',	'Калининградская область',	'Калужская область',	'Камчатская область',	'Кемеровская область',	'Кировская область',	'Корякский автономный округ',	'Костромская область',	'Краснодарский край',	'Красноярский край',	'Курганская область',	'Курская область',	'Ленинградская область',	'Липецкая область',	'Магаданская область',	'Московская область',	'Мурманская область',	'Ненецкий автономный округ',	'Нижегородская область',	'Новгородская область',	'Новосибирская область',	'Омская область',	'Оренбургская область',	'Орловская область',	'Пензенская область',	'Пермская область',	'Пермятский автономный округ',	'Приморский край',	'Псковская область',	'Республика Алтай',	'Республика Башкортостан',	'Республика Бурятия',	'Республика Дагестан',	'Республика Кабардино-Балкария',	'Республика Карачаево-Черкессия',	'Республика Карелия',	'Республика Коми',	'Республика Марий-Эл',	'Республика Мордовия',	'Республика Саха (Якутия)',	'Республика Татарстан',	'Республика Тува',	'Республика Удмуртия',	'Республика Хакассия',	'Республика Чувашия',	'Ростовская область',	'Рязанская область',	'Самарская область',	'Саратовская область',	'Сахалинская область',	'Свердловская область',	'Смоленская область',	'Ставропольский Край',	'Таймырский автономный округ',	'Тамбовская область',	'Тверская область',	'Томская область',	'Тульская область',	'Тюменская область',	'Ульяновская область',	'Усть-Ордынский автономный округ',	'Хабаровский край',	'Ханты-Мансийский автономный округ',	'Челябинская область',	'Читинская область',	'Чукотский автономный округ',	'Эвенкийский автономный округ',	'Ямало-Ненецкий автономный округ',	'Ярославская область']
	# end

	def getDistricts
		['Октябрьский','Первомайский','Ленинский','Железнодорожный']
	end

	def getOwnerForm
		{'Вторичка ' => 0, 'Новострой' => 1}
	end
	

end

app/views/sale_objects/_block_left.html.slim
p.block_head Местоположение
.field   
 =f.label :region 
 =f.select :region, @regions || []
 span *
.field
 =f.select :locality_type, getLocalityType,{},{style: "width: 100px; margin-right: 10px;"}
 =f.text_field :locality, required: true  
 span *
/ .field
/  =f.label :area
/  =f.text_field :area
.field
 =f.label :district
 =f.select :district, @districts || []
.field
 =f.select :street_type, getStreetType,{},style: "width: 100px; margin-right: 10px;"
 =f.text_field :street, required: true  
 span *
.field
 =f.select :object_type, getObjectType,{},style: "width: 100px; margin-right: 10px;"
 =f.text_field :object, style: "margin-right: 20px; width: 80px;"  
 =f.label :letter, style: "width: 100px"
 =f.text_field :letter,  title: "Буква", style: "width: 40px;"
.field
  =f.check_box :show_number,  title: "Показывать номер дома"
  =f.label :show_number,"Показывать номер дома", style: "width: 160px; margin-left: 10px; margin-top: 10px;"  
.field
 =f.select :block_type, getBlockType, {}, style:"width: 100px;  margin-right: 10px;" 
 =f.text_field :block, style: "margin-right: 20px; width: 80px;"
 =f.label :flat, style: "width: 100px"
 =f.text_field :flat, title: "Квартира", style: "width: 40px;"
.field
 =f.label :index
 =f.text_field :index, style: "width: 130px;"
.field
 =f.label :station_metro
 =f.text_field :station_metro
p.block_head Сопровождение
.field
 =f.label :agency
 =f.select :agency, getOperator
.field
 =f.label :personal
 =f.select :personal_id, @personals || []
.field
 =f.label :status
 =f.select :status, getStatus
.field 
 =f.label :begin_contract,  style: "padding-right: 10px; font-weight:bold"    
 =f.date_field :begin_contract, style: "width: 150px;"
 span *
.field
 =f.label :end_contract, style: "padding-right: 10px;font-weight:bold;"
 =f.date_field :end_contract, style: "width: 150px;"
p.block_head Личные данные
.field
 =f.label :owner
 =f.text_field :owner
.field
 =f.label :owner_phone, 'Телефон владельца'
 =f.text_field :owner_phone, style: "width: 130px;"
.field
 =f.label :price
 =f.text_field :price, required: true, style: "width: 100px;"
 span &nbsp;*
 span &nbsp;руб.
 div style="display: inline-block; width: 130px; margin-left: 10px;"
  =f.check_box :hide_price, {style: "width: 20px; margin-bottom: 7px;"}
  =f.label :hide_price, style: "width: 100px;"
.field
 =f.label :client_request 
 =f.text_field :client_request
.field
 =f.label :client_phone 
 =f.text_field :client_phone, style: "width: 130px;"
.field   
 =f.label :finaly_price
 =f.text_field :finaly_price, style: "width: 130px;"
.field 
 =f.label :date
 =f.date_field :date, style: "width: 150px;"

app/views/sale_objects/_error_messages.html.slim
- if @sale_object.errors.any?
  #error_explanation    
    ul
      - @sale_object.errors.full_messages.each do |msg|
        li= msg

app/views/sale_objects/_other_status.html.slim
.count="Объектов найдено: #{@count}"
table.sale_object_index
 tr
  th № 
  th Адрес
  th Дата
  th Тип
  th Комнат
  th Статус
  th Цена
  th Фото
  th Риелтор
  th Гор. предл.
  -i = 0
 -@sale_objects.each do |record|
  tr bgcolor="#{record.agreement.zero? ? '' : '#EFC2C2'}"
   td= i +=1
   td.name= link_to getAdressString(record), edit_sale_object_path(record)
   td= record.created_at.strftime("%d.%m.%Y")
   td= record.structure_type
   td= record.rooms_count
   td= getStatusName record.status
   td= number_to_currency record.price if record.hide_price.zero?
   td 
   td= "#{record.personal.sename} #{record.personal.name}" unless record.personal.nil?  
   / # td= check_box_tag :hot_offer,record.id, record.hot_offer
   -if record.hot_offer.zero?
    td= image_tag 'unhot.png', title: "Не горячее предложение", class: 'hot', data: {id: record.id, val: 1}
   -unless record.hot_offer.zero? 
    td= image_tag 'hot.png', title: "Горячее предложение", class: 'hot', data: {id: record.id, val: 0}

app/views/sale_objects/_sold_arenda.html.slim
.count="Объектов найдено: #{@count}"
table.sale_object_index
 tr
  th № 
  th Адрес
  th Дата начала
  th Тип  
  th Статус
  th Цена начальная
  th Цена конечная  
  th Риелтор  
  -i = 0
 -@sale_objects.each do |record|
  tr bgcolor="#{record.agreement.zero? ? '' : '#EFC2C2'}"
   td= i +=1
   td.name= link_to getAdressString(record), edit_sale_object_path(record)
   td= record.begin_contract.strftime("%d.%m.%Y")
   td= record.structure_type   
   td= getStatusName record.status
   td= number_to_currency record.price if record.hide_price.zero?
   td= number_to_currency record.finaly_price if record.hide_price.zero? 
   td= "#{record.personal.sename} #{record.personal.name}" unless record.personal.nil?  
   

app/views/sale_objects/edit.html.slim
-content_for :links do
  p=link_to 'Назад', sale_objects_path  
  br
  p=link_to "Сохранить", "#", onclick:"$('form').submit()"
  p=link_to 'Удалить', {action: :destroy}, confirm: "Удалить объект", method: :delete
  p=link_to "Аванс", avans_sale_object_path, method: 'patch' unless @sale_object.avans
  p=link_to "Продано", sold_sale_object_path, method: 'patch' unless @sale_object.sold
  p=link_to "Истек срок договора", expired_sale_object_path, method: 'patch' unless @sale_object.expired
    
.title Редактировать объект
-unless @sale_object.avans.zero?
 .avans Объект под авансом
-unless @sale_object.sold.zero?
 .sold Объект продан 
-unless @sale_object.expired.zero?
 .expired Истек срок договора
=render 'error_messages' 
-@districts = []  
-District.select(:name).where(region_id: @sale_object.region).each do |district| 
 -@districts << district.name
=form_for @sale_object, :html => {:multipart => true} do |f|   
 -sale_object = SaleObject.find(params[:id])
 -structure_type = sale_object.structure_type
 -owner_form = sale_object.owner_form
 -if getTypeLived.include?(structure_type)
  =hidden_field_tag :structure_type_select, 1
  -type = 1
  -@get_type = getTypeLived
 -else 
  =hidden_field_tag :structure_type_select, 2
  -type = 2
  -@get_type = getTypeCommerc
 -if owner_form == 1
  -single_or_half = 1
 -else
  -single_or_half = 2
 table.sale_object class="table"
  tr
   td    
    =render partial: "block_left", locals: {f: f}
   td    
    =render partial: "block_right", locals: { f: f, type: type, structure_type: structure_type, single_or_half: single_or_half }  

app/views/sale_objects/index.html.slim
=content_for :links do
 p=link_to 'Назад', admin_path
 br
 p=link_to "Добавить объект", new_sale_object_path 
 br
 / p=link_to "Текущие объекты", sale_objects_path(status: 3), id: "current_objects"
 / p=link_to "Под авансом", sale_objects_path(status: 5), id: "presentation"
 / p=link_to "Бывшие объекты", sale_objects_path(status: 7), id: "olds_objects"
 / p=link_to "Все объекты", sale_objects_path(status: 0), id: "all_objects"
.title Создание и редактирование объектов
#find_sale_object
 p#find_link Найти
 =form_for :filter, url: {action: :filter} do |f|
  .field
   =f.label :from, "С:", style: "font-size: 14px;font-weight: bold; width: 65px;display: inline-block; "
   =f.date_field :from, style: "width: 140px;"
 
   =f.label :to, "По:", style: "font-size: 14px;font-weight: bold; width: 65px;display: inline-block; margin-left: 55px;"
   =f.date_field :to,  style: "width: 140px;" 
  .field
   =f.label :structure_type, "Тип", style: "font-size: 14px;font-weight: bold; width: 65px;display: inline-block;"
   =f.select :structure_type, getTypeAll, {prompt: "Все"},  style: "width: 170px;"    
  
   =f.label :status, "Статус", style: "font-size: 14px;font-weight: bold; width: 65px;display: inline-block; margin-left: 24px;" 
   =f.select :status, getStatus,  {prompt: "Все"},  style: "width: 170px;" 
  .field
   =f.label :rooms_count, "Комнат", style: "font-size: 14px;font-weight: bold; width: 65px;display: inline-block;" 
   =f.select :rooms_count, [1,2,3,4,5], {prompt: "Все"},  style: "width: 70px;"

   =f.label :street, "Улица", style: "font-size: 14px;font-weight: bold; width: 65px;display: inline-block; margin-left: 124px;" 
   =f.select :street, @streets || [], {prompt: "Все"},  style: "width: 320px;"   
  .submit
   =f.submit "Найти"

-if !@sale_objects.take.nil? && @sale_objects.take.status == 6 
 =render 'sold_arenda' 
-else  
 =render 'other_status'

app/views/sale_objects/new.html.slim
-content_for :links do
 p=link_to 'Назад', sale_objects_path
 br
 p=link_to "Сохранить", "#", onclick:"$('form').submit()"
 
.title Добавить объект
=render 'error_messages'
=form_for @sale_object, :html => {:multipart => true} do |f|  
 -type = 1
 -structure_type = 1
 -single_or_half = 1
 table.sale_object class="table"
  tr
   td    
    =render partial: "block_left", locals: {f: f}
   td    
    =render partial: "block_right", locals: { f: f, type: type, structure_type: structure_type, single_or_half: single_or_half }
 

app/views/sale_objects/show.html.slim
h1 SaleObjects#show
p Find me in app/views/sale_objects/show.html.slim