config/routes.rb
Kirsh::Application.routes.draw do


  get "help_informations/index"
  get "help_informations/new"
  get "help_informations/edit"
  get "select_objects/new"
  get "select_objects/edit"
  mount Ckeditor::Engine => '/ckeditor'
  root 'sites#index'


  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  get 'admin' => 'admins#index'
  get 'yamail' => 'sites#yamail'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :user_accounts
  resources :effective_rieltors
  resources :personals
  resources :client_requests do
    post :load_request, on: :collection
    post :check_phone, on: :collection
  end
  resources :client_request_without_objects do
    post :load_request, on: :collection
  end
  resources :sale_objects do
    member do
      patch :hot_offer
      patch :avans
      patch :sold
      patch :expired
      get :photo_delete
    end
    resources :photo, only: [:create, :destroy]
    post :getDistricts, on: :collection
    post :filter, on: :collection
  end
  resources :sites do
   collection do
    get :about
    get :question_answer
    get :contacts
    get :zalog
    get :buyout
    get :kredit
    get :agents
    get :own_biznes
    get :developer
    get :owner_komerch
    get :search
    post :search_request
    get :request_user
    get :request_advert
    post :send_request
    post :send_request_advert
    post :question_answer_create
    post :consultant
    post :search_map
    get :map_site
    get :map_site_print
    get :document_example
   end
   get :object_detail, on: :member
   get :print, on: :member
  end
  resources :abouts
  resources :answers
  resources :developers
  resources :owner_komerches
  resources :kredits
  resources :zalogs
  resources :buyouts
  resources :bisnes_selfs
  resources :agents
  resources :regions
  resources :news_on_sites do
    get :admin_index, on: :collection
    get :public, on: :member
  end
  resources :main_pages
  resources :districts
  resources :seos
  resources :top_banners
  resources :papers do
    get :site_index, on: :collection
  end
  resources :tests
  resources :select_objects
  resources :help_informations

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/agent.rb
class Agent < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  accepts_nested_attributes_for :question
end

app/models/buyout.rb
class Buyout < ActiveRecord::Base
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_one :client_request

	validates :phone, :name, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/developer.rb
class Developer < ActiveRecord::Base
end

app/models/district.rb
class District < ActiveRecord::Base
	belongs_to :region
end

app/models/foreign.rb
class Foreign < ActiveRecord::Base
end

app/models/franshisa.rb
class Franshisa < ActiveRecord::Base
end

app/models/kredit.rb
class Kredit < ActiveRecord::Base
end

app/models/main_page.rb
class MainPage < ActiveRecord::Base
end

app/models/paper.rb
class Paper < ActiveRecord::Base
	 mount_uploader :file, FileUploader
	 validates :title, presence: true
end

app/models/partner.rb
class Partner < ActiveRecord::Base
end

app/models/personal.rb
class Personal < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
	belongs_to :user_account
	has_many :client_requests
    has_many :sale_objects, dependent: :nullify 


	scope :rieltor, -> {where(position: 15)}

	validates :sename, :name, :status, :position, :agency, :begin_job, :mobile_phone, presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	# mount_uploader :photo, PhotoUploader
	belongs_to :sale_object, polymorphic: true 
end

app/models/question.rb
# encoding: utf-8

class Question < ActiveRecord::Base
	apply_simple_captcha :message => "Не правильно введен код с картинки"
	has_one :answer, dependent: :destroy 
	validates :name, :question, :email, presence: true

	scope :public, ->{where(is_public: 1)}

end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :districts
end

app/models/seo.rb
class Seo < ActiveRecord::Base
end

app/models/test.rb
class Test 
	include ActiveModel::Model
	
	attr_accessor :fio, :email, :phone, :question1, :question2, :question3, :question4, :question5, :question6

	validates :fio, :email, :phone, presence: true

	def summ
		question1.to_i+question2.to_i+question3.to_i+question4.to_i+question5.to_i+question6.to_i
	end

end

app/models/zalog.rb
class Zalog < ActiveRecord::Base
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
  	@questions = Question.all
  end

  def edit
  	@answer = Answer.find params[:id]
  end

  def new
  	@answer = Answer.new
  	@question = Question.find params[:id]
  end

  def create
  	if @answer = Answer.create(params_hash)
  		QuestionMailer.new_answer(@answer.question.email).deliver unless @answer.question.email.nil?
      q = Question.find @answer.question.id
      q.update(is_public: 1)
  		redirect_to answers_path
  	else
  		render 'new'
  	end
  end

  def update
  	@answer = Answer.find params[:id]
  	if @answer.update(params_hash)
  		redirect_to answers_path(type: 2)
  	else
  		render 'edit'
  	end
  end

  def destroy
  	Question.find(params[:id]).destroy
  	redirect_to answers_path
  end

private

	def params_hash
		params.require(:answer).permit!
	end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/edit.html.slim
.title= "#{@answer.question.name} спрашивает:"
h4= @answer.question.question 
p.answer_contacts= "Телефон:&nbsp; #{@answer.question.phone unless @answer.question.phone.blank?}".html_safe
p.answer_contacts= "Email:&nbsp; #{mail_to @answer.question.email}".html_safe
=content_for :links do
 p=link_to "Назад", answers_path(type: 2)
 br
 p=link_to "Сохранить", "#", onclick: "$('form').submit()"  
 
=form_for @answer do |f|   
 .field
  =f.fields_for :question do |q|
   =q.check_box :is_public, style: "float: left; margin-right: 10px;"
   =q.label :is_public, 'Опубликованно'
   =q.hidden_field :email, value: @answer.question.email 
  =f.label :answer
  =f.cktext_area :answer,  cols: 20, ckeditor:  {language: "ru"} 
  

app/views/answers/index.html.slim
.title Вопрос-ответ
=content_for :links do
 p=link_to "Назад", admin_path
 br
 p=link_to "Без ответов", answers_path(type: 1), id: "without_answers"
 p=link_to "С ответами", answers_path(type: 2), id: "with_answers" 
 p=link_to "Все", answers_path(type: 3), id: "all_answers"
.questions_list
 ul style="list-style: decimal"
  -@questions.each do |question|
  -case params[:type].to_i
   -when 1
    -if question.answer.nil?
     li
      =link_to question.question, new_answer_path(id: question)
      span       
       =link_to " #{delete}".html_safe, answer_path(question.id), method: :delete, confirm: "Удалить вопрос?"
   -when 2
    -unless question.answer.nil?
     li
      =link_to question.question, edit_answer_path(question.answer) 
      span       
       =link_to " #{delete}".html_safe, answer_path(question.id), method: :delete, confirm: "Удалить вопрос?"
   -when 3     
     li
      =link_to question.question, new_answer_path(id: question) if question.answer.nil?
      =link_to question.question, edit_answer_path(question.answer) unless question.answer.nil?
      span       
       =link_to " #{delete}".html_safe, answer_path(question.id), method: :delete, confirm: "Удалить вопрос?"
   -else
    -if question.answer.nil?
     li
      =link_to question.question, new_answer_path(id: question)
      span       
       =link_to " #{delete}".html_safe, answer_path(question.id), method: :delete, confirm: "Удалить вопрос?"

app/views/answers/new.html.slim
.title= "#{@question.name} спрашивает:"
h4= @question.question 
p.answer_contacts= "Телефон:&nbsp; #{@question.phone unless @question.phone.blank?}".html_safe
p.answer_contacts= "Email:&nbsp; #{mail_to @question.email}".html_safe
=content_for :links do
 p=link_to "Назад", answers_path
 br
 p=link_to "Сохранить", "#", onclick: "$('form').submit()"  
=form_for @answer do |f|   
 .field  
  =f.label :answer
  =f.cktext_area :answer,  cols: 20, ckeditor:  {language: "ru"} 
  =f.hidden_field :question_id, value: params[:id]