config/routes.rb
Kirsh::Application.routes.draw do


  get "help_informations/index"
  get "help_informations/new"
  get "help_informations/edit"
  get "select_objects/new"
  get "select_objects/edit"
  mount Ckeditor::Engine => '/ckeditor'
  root 'sites#index'


  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  get 'admin' => 'admins#index'
  get 'yamail' => 'sites#yamail'

  resources :sessions, :only => [:new, :create, :destroy]
  resources :user_accounts
  resources :effective_rieltors
  resources :personals
  resources :client_requests do
    post :load_request, on: :collection
    post :check_phone, on: :collection
  end
  resources :client_request_without_objects do
    post :load_request, on: :collection
  end
  resources :sale_objects do
    member do
      patch :hot_offer
      patch :avans
      patch :sold
      patch :expired
      get :photo_delete
    end
    resources :photo, only: [:create, :destroy]
    post :getDistricts, on: :collection
    post :filter, on: :collection
  end
  resources :sites do
   collection do
    get :about
    get :question_answer
    get :contacts
    get :zalog
    get :buyout
    get :kredit
    get :agents
    get :own_biznes
    get :developer
    get :owner_komerch
    get :search
    post :search_request
    get :request_user
    get :request_advert
    post :send_request
    post :send_request_advert
    post :question_answer_create
    post :consultant
    post :search_map
    get :map_site
    get :map_site_print
    get :document_example
   end
   get :object_detail, on: :member
   get :print, on: :member
  end
  resources :abouts
  resources :answers
  resources :developers
  resources :owner_komerches
  resources :kredits
  resources :zalogs
  resources :buyouts
  resources :bisnes_selfs
  resources :agents
  resources :regions
  resources :news_on_sites do
    get :admin_index, on: :collection
    get :public, on: :member
  end
  resources :main_pages
  resources :districts
  resources :seos
  resources :top_banners
  resources :papers do
    get :site_index, on: :collection
  end
  resources :tests
  resources :select_objects
  resources :help_informations

end

app/models/client_request.rb
# encoding: utf-8

class ClientRequest < ActiveRecord::Base
  belongs_to :client
  belongs_to :sale_object
  belongs_to :personal  

  accepts_nested_attributes_for :client
  scope :treatment, -> {where(status: 1)}	
  scope :accompanied, -> {where(status:[2,3])}

  validates  :personal_id, :sale_object_id, presence: true

  after_save do
  	client = Smspilot.new "H69SXX2EXAP3E2TI92W03GTT955PQ9ZLFSQXSO51C1NH65K57TZIUDF88YTPK024"    
    result = client.send_sms(self.id, 'KIRSH', self.personal.mobile_phone.delete('-'), "#{self.client.name}, тел. #{self.client.phone}, #{self.sale_object.street_type}#{self.sale_object.street} #{self.sale_object.object_type} #{self.sale_object.object}#{self.sale_object.letter} #{self.sale_object.block_type unless self.sale_object.block.blank?}#{self.sale_object.block}#{',' unless self.comment.blank?} #{self.comment}")
  end

end

app/controllers/client_requests_controller.rb
# encoding: utf-8
class ClientRequestsController < ApplicationController
  include SaleObjectsHelper

  before_filter only: [:index, :edit, :new, :load_request] do 
    @personals = {}    
    Personal.where(status: 1).order("sename ASC").each { |persona| @personals["#{persona.sename} #{persona.name}"] = persona.id}
  end  

  before_filter only: [:new, :edit] do
    
    @regions = {}
    @districts = []
    @objects = SaleObject.where(status:[3])
    Region.all.each {|region| @regions[region.name] = region.id}
    if Region.exists? 1
      region = Region.find 1
      if region.districts.any?
       region.districts.order("name ASC").each do |district|
        @districts << district.name
       end
      end
    end
  end
  


  def index
   @dates =[]
   dates_from_db = ClientRequest.select(:created_at).group(:created_at)
   dates_from_db.each {|date| @dates << date[:created_at].strftime('%m.%Y')}
   @dates.uniq!
  
   if params[:date].nil?  	    
    last = @dates.last
    last = last.split('.')
    year_last = last[1].to_i
    month_last = last[0].to_i
    end_day = Date.civil(year_last, month_last, -1).day   
    @client_requests = ClientRequest.where(created_at: ["#{year_last}-#{month_last}-01".."#{year_last}-#{month_last}-#{end_day}"])
   else 
    param = params[:date].split('.')
    year = param[1].to_i
    month = param[0].to_i
    end_day = Date.civil(year, month, -1).day   
    @client_requests = ClientRequest.where(created_at: ["#{year}-#{month}-01".."#{year}-#{month}-#{end_day}"])
   end 
   # render text: ["#{year}-#{month}-01".."#{year}-#{month}-#{end_day}"]
   @count = @client_requests.count
   
  end

  def new
    @client_request = ClientRequest.new  
    @client_request.build_client
  end

  def create
    @client_request = ClientRequest.new(post_params)      
    if @client_request.save()     
      redirect_to client_requests_path, notice: "Проспект добавлен"
    else
      render 'new'
    end
  end

  def edit
    @client_request = ClientRequest.find params[:id] 
  end

  def update
    @client_request = ClientRequest.find params[:id] 
    if @client_request.update(post_params)
      redirect_to client_requests_path, notice: "Проспект отредактирован"
    else
      render 'edit'
    end
  end

  def show
  end

  def load_request
   
   from = params[:filter][:from]
   to = params[:filter][:to]
   type = params[:filter][:type]
   rooms_count = params[:filter][:rooms_count]
   status = params[:filter][:status]
   rieltor = params[:filter][:rieltor]
   query = {}
   query[:created_at] = [from..to] unless from.blank? && to.blank?
   query[:structure_type] = type unless type.blank?
   query[:status] = status unless status.blank?
   query[:rooms_count] = rooms_count unless rooms_count.blank?   
   query[:personal_id] = rieltor unless rieltor.blank? 

   @client_requests = ClientRequest.includes(:sale_object).where(query)
   @count = @client_requests.count 
   render 'index'
  end

  def check_phone
    if Client.where(phone: params[:phone]).take
      render text: 1
    else
      render text: 0
    end
  end

  def destroy
    if ClientRequest.find(params[:id]).destroy
      redirect_to client_requests_path, notice: "Проспект удален"
    else
      redirect_to client_requests_path, notice: "Проспект не удален"
    end
  end

private
  
  def post_params
    params.require(:client_request).permit!    
  end    
end

app/helpers/client_requests_helper.rb
# encoding: utf-8

module ClientRequestsHelper

	def getClientRequestStatus
		{"обратился" => 1, "сопровождается" => 2, "купил в КИРШ" => 3, "купил не в КИРШ" => 4, "прервал сопровождение" => 5}	
	end

	def getClientRequestWitoutObject
		{"обратился" => 1, "сопровождается" => 2}
	end

	def getClientRequestStatusName id
		 getClientRequestStatus.key(id)
	end

	def getAccess
		{"Риэлтор" =>1, "Офис" =>2, "Все" =>0}
	end

	def getFinancing
		["накопление","ипотека","обмен","обмен с доплатой","обмен с профитом"]
	end

	def getFloor
		["любой","1","2","последний","не 1","не последний"," не 1, не последний"]
	end

	def getTypeWitoutObject
		["Квартиры","Комнаты","Городские дома","Загородные дома","Зем.участки","Гаражи","Дачи", "Коммерческая недвижимость","Займ", "Ипотека", "Срочный выкуп", "Продажа"]
	end

end

app/views/client_requests/_block_1.html.slim
td
 =f.fields_for :client do |c|
  .field
   =c.label :phone
   =c.text_field :phone
   span *
  .field
   =c.label :name
   =c.text_field :name
   span *
  / .field
  /  =c.label :sename
  /  =c.text_field :sename
  .field
   =c.label :email
   =c.text_field :email  
  / .field
  /  =c.label :sex
  /  =c.radio_button :sex, 1, checked: true
  /  =label_tag :client_request_sex_0, 'М', class: "check_radio_box_labels"
  /  =c.radio_button :sex, 2
  /  =label_tag :client_request_sex_1, 'Ж', class: "check_radio_box_labels"
 .field
  =f.label :offer_type 
  =f.radio_button :offer_type, 0, checked: true
  =label_tag :client_request_offer_type_0, 'Купить', class: "check_radio_box_labels"
  =f.radio_button :offer_type, 1
  =label_tag :client_request_offer_type_1, 'Снять', class: "check_radio_box_labels"
td
 .field
  =f.label :operator
  =f.select :operator, getOperator
 .field
  =f.label :access
  =f.select :access, getAccess
 .field
  =f.label :status
  =f.select :status, getClientRequestStatus
 .field
  =f.label :agent
  =f.radio_button :agent, 0, checked: true
  =label_tag :client_request_agent_0, 'Нет', class: "check_radio_box_labels"
  =f.radio_button :agent, 1
  =label_tag :client_request_agent_1, 'Да', class: "check_radio_box_labels"
 .field
  =f.label :financing
  =f.select :financing, getFinancing

app/views/client_requests/_block_2.html.slim
td 
 .field
  =f.label :personal_id
  =f.select :personal_id, @personals || []
 .field
  =f.label :sale_object_id
  =f.select :sale_object_id, options_for_select(@objects.order("street ASC").collect { |object| ["#{object.structure_type} #{object.street_type} #{object.street} #{object.object_type} #{object.object}#{object.letter} #{object.block_type unless object.block.blank? } #{object.block}", object.id,{id: object.personal_id}] })
td
 .field
  =f.label :date_reg
  =f.date_field :date_reg

app/views/client_requests/_block_3.html.slim
td
 .field
  =f.label :region
  =f.select :region, @regions || []
 .field  
  =f.select :locality_type,getLocalityType,{},style: "width: 23%; margin-right: 31px;"
  =f.text_field :locality
td  
 .field
  =f.label :district
  =f.select :district, @districts || []
 .field
  =f.label :station_metro
  =f.text_field :station_metro
/ td
/  .field
/   =f.label :area  
/   =f.select :area,getAreas

app/views/client_requests/_block_4.html.slim
td
 .field
  =f.label :structure_type
  =f.select :structure_type, getType
 .field.rooms
  =f.label :rooms_count
  =f.text_field :rooms_count, style: "width: 60px"
 / .field
 /  =f.label :min_square
 /  =f.text_field :min_square, style: "width: 60px"
 /  span м<sup>2</sup>
 / .field
 /  =f.label :max_price
 /  =f.text_field :max_price, style: "width: 100px"
 /  span руб.
td
 / .field
 /  =f.label :floor
 /  =f.select :floor, getFloor
 / .field
 /  =f.label :material
 /  =f.select :material, getMaterial 
 / .field
 /  =f.label :balkon 
 /  =f.radio_button :balkon, 1
 /  =label_tag :client_request_balkon_1, 'Важно', class: "check_radio_box_labels"
 /  =f.radio_button :balkon, 0
 /  =label_tag :client_request_balkon_0, 'Нет', class: "check_radio_box_labels"
 / .field
 /  =f.label :parking 
 /  =f.radio_button :parking, 1
 /  =label_tag :client_request_parking_1, 'Важно', class: "check_radio_box_labels"
 /  =f.radio_button :parking, 0
 /  =label_tag :client_request_parking_0, 'Нет', class: "check_radio_box_labels"  
 .field
  =f.label :comment, "Коментарий"
  =f.text_area :comment
coffee:
 $(document).on 'change', '#client_request_structure_type', ->
  if @.value == 'Комнаты' || @.value == 'Зем. участки' || @.value == 'Гаражи'
   $('.rooms').hide()
  else
   $('.rooms').show() 

app/views/client_requests/_error_messages.html.slim
- if @client_request.errors.any?
  #error_explanation    
    ul
      - @client_request.errors.full_messages.each do |msg|
        li= msg

app/views/client_requests/edit.html.slim
.title Редактирование проспекта
=content_for :links do
 p=link_to "Назад", client_requests_path
 br
 p=link_to "Сохранить", "#", onclick: "$('form').submit()" 
 p=link_to "Удалить", @client_request, method: :delete, confirm: "Удалить проспект?"   
=render 'error_messages'  
=form_for @client_request do |f|
 table.client_requests class="table"
  tr     
   =render partial: "block_1", locals: {f: f}
  tr 
   td.block_head colspan=2 Персональные данные       
  tr 
   =render partial: "block_2", locals: { f: f } 
  tr 
   td.block_head colspan=2 Местоположение
  tr
   =render partial: "block_3", locals: { f: f }   
  tr 
   td.block_head colspan=2 Параметры
  tr
   =render partial: "block_4", locals: { f: f }  

app/views/client_requests/index.html.slim
.title Создание и редактирование проспектов
=content_for :links do
 p=link_to "Назад", admin_path
 br
 p=link_to "Добавить", new_client_request_path 
 br 
 p=link_to "Проспекты без привязки к объекту", client_request_without_objects_path 

#find
 p#find_link Найти
 =form_for :filter, url: {action: :load_request} do |f|
  .field
   =f.label :from, "С:", style: "font-size: 14px;font-weight: bold; width: 65px;display: inline-block; "
   =f.date_field :from, style: "width: 130px;"
 
   =f.label :to, "По:", style: "font-size: 14px;font-weight: bold; width: 130px;display: inline-block; margin-left: 55px;"
   =f.date_field :to,  style: "width: 130px;" 
  .field
   =f.label :type, "Тип", style: "font-size: 14px;font-weight: bold; width: 65px;display: inline-block;"
   =f.select :type, getType, {prompt: "Все"},  style: "width: 170px;" 
 
   =f.label :rooms_count, "Кол-во комнат", style: "font-size: 14px;font-weight: bold; width: 130px;display: inline-block; margin-left: 16px;" 
   =f.select :rooms_count, [1,2,3,4,5],  {prompt: "Все"},  style: "width: 60px;" 
  .field
   =f.label :status, "Статус", style: "font-size: 14px;font-weight: bold; width: 65px;display: inline-block;" 
   =f.select :status, {"Обратившиеся" => 1, "Текущие проспекты" => 2, "Бывшие проспекты" => [3,4,5]},  {prompt: "Все"},  style: "width: 170px;" 
 
   =f.label :rieltor, "Риэлтор", style: "font-size: 14px;font-weight: bold; width: 130px;display: inline-block; margin-left: 16px;" 
   =f.select :rieltor, @personals || [], {prompt: "Все"},  style: "width: 320px;"
  .submit
   =f.submit "Найти"  
.count= "Найдено проспектов: #{@count}"  
-i = 1
.dates
 unless @dates.nil?
  -@dates.each do |date|
   =link_to date, client_requests_path(date: date), title: "Вывести все проспекты за #{date}"
table.client_request_index 
 tr
  / th №
  th Телефон
  th ФИО
  th Дата
  / th Агент
  / th Способ
  th Тип
  th Комнат
  / th кв. м
  / th Цена
  / th Финанс.
  / th Ст. метро/район
  th Риэлтор
  th Начальный объект
 -@client_requests.each do |clients_request|
  tr
   / td= i +=1
   td= clients_request.client.phone unless clients_request.status == 2
   td= link_to "#{clients_request.client.name}", edit_client_request_path(clients_request)
   td= clients_request.created_at.strftime("%d.%m.%Y")   
   / td= clients_request.agent ? "Да" : "Нет"
   / td= getClientRequestStatusName clients_request.status
   td= clients_request.structure_type
   td= clients_request.rooms_count
   / td= clients_request.min_square
   / td= number_to_currency clients_request.max_price
   / td= clients_request.financing
   / td= clients_request.station_metro
   td= "#{clients_request.personal.sename unless clients_request.personal.nil?} #{clients_request.personal.name unless clients_request.personal.nil?}"
   td= getAdressString clients_request.sale_object unless clients_request.sale_object.nil? 

app/views/client_requests/new.html.slim
.title Добавление нового проспекта
=content_for :links do
 p=link_to "Назад", client_requests_path
 br
 p=link_to "Сохранить", "#", onclick: "$('form').submit()"
 / p id="check_phone" Проверить телефон 
 / p id="check_phone_message"
=render 'error_messages'  
=form_for @client_request do |f|
 table.client_requests class="table"
  tr     
   =render partial: "block_1", locals: {f: f}
  tr 
   td.block_head colspan=2 Персональные данные       
  tr 
   =render partial: "block_2", locals: { f: f } 
  tr 
  /  td.block_head colspan=2 Местоположение
  / tr
  /  =render partial: "block_3", locals: { f: f }   
  tr 
   td.block_head colspan=2 Параметры
  tr
   =render partial: "block_4", locals: { f: f }  

app/views/client_requests/show.html.slim
h1 ClientRequests#show
p Find me in app/views/client_requests/show.html.slim